baseurl = "https://muryp.my.id/"
title = "MuryP Beta"
theme = "muryp"
disqusShortname = "muryp"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  author = "authors"

[permalinks]
  blog = "/blog/:slug/"
  laman = "/pages/:slug/"
  # en = "/en/:slug/"

languageCode = "id-id"
DefaultContentLanguage = "id"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

