[[contact]]
identifier = "@muryp"
name = "telegram"
url = "https://t.me/muryp"
weight = 1
[[contact]]
identifier = "alifmuryp@gmail.com"
name = "gmail"
url = "mailto:alifmuryp@gmail.com"
weight = 2
[[contact]]
identifier = "+6283 829 383 123"
name = "tlp"
url = "wa_link"
weight = 3
# Ask me
[[ask]]
identifier = "@alifmuryp"
name = "twitter"
url = "https://twitter.com/murypstudio"
weight = 1
[[ask]]
identifier = "Muryp Beta"
name = "facebook"
url = "https://facebook.com/muryp"
weight = 2